export const module2Questions = [
  {
    id: 'm2-q001',
    moduleId: 'm2',
    difficulty: 'basic',
    topic: 'higiene-digital',
    question: 'Qual alternativa define melhor higiene digital?',
    options: [
      'Um conjunto de hábitos preventivos para reduzir riscos no uso de contas, dispositivos, dados e serviços digitais.',
      'Uma ferramenta única que elimina todos os golpes digitais.',
      'Uma prática restrita a especialistas em programação e perícia digital.',
      'Uma reação emergencial adotada apenas depois que o incidente acontece.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q002',
    moduleId: 'm2',
    difficulty: 'basic',
    topic: 'senha-forte',
    question: 'Qual característica é mais importante em uma senha segura?',
    options: [
      'Ser curta e fácil de digitar.',
      'Ser reutilizada em várias contas para facilitar a memorização.',
      'Ser longa, única e difícil de adivinhar.',
      'Ser baseada no nome de familiares ou datas importantes.',
    ],
    answer: 2,
  },
  {
    id: 'm2-q003',
    moduleId: 'm2',
    difficulty: 'basic',
    topic: 'senhas-unicas',
    question: 'Por que não é recomendável usar a mesma senha em vários serviços?',
    options: [
      'Porque senhas repetidas deixam de funcionar tecnicamente.',
      'Porque, se uma senha vazar em um serviço, outras contas que usam a mesma senha também ficam em risco.',
      'Porque serviços digitais exigem sempre senhas completamente públicas.',
      'Porque senhas repetidas impedem o uso de internet banking.',
    ],
    answer: 1,
  },
  {
    id: 'm2-q004',
    moduleId: 'm2',
    difficulty: 'basic',
    topic: '2fa',
    question: 'Qual é a função principal da verificação em duas etapas?',
    options: [
      'Substituir qualquer necessidade de senha.',
      'Adicionar uma segunda camada de proteção ao acesso à conta.',
      'Permitir que senhas sejam compartilhadas com segurança.',
      'Evitar que o usuário precise atualizar aplicativos.',
    ],
    answer: 1,
  },
  {
    id: 'm2-q005',
    moduleId: 'm2',
    difficulty: 'basic',
    topic: 'email',
    question: 'Por que a conta de e-mail deve ser tratada como conta crítica?',
    options: [
      'Porque o e-mail geralmente permite redefinir senhas de outros serviços.',
      'Porque o e-mail não armazena dados relevantes.',
      'Porque a conta de e-mail nunca é alvo de criminosos.',
      'Porque o e-mail substitui o backup dos arquivos pessoais.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q006',
    moduleId: 'm2',
    difficulty: 'basic',
    topic: 'backup',
    question: 'Qual é a finalidade principal do backup?',
    options: [
      'Aumentar o desempenho de jogos e vídeos.',
      'Permitir recuperação de dados em caso de perda, falha, furto, exclusão indevida ou ataque.',
      'Impedir que qualquer golpe seja praticado.',
      'Substituir senhas fortes e autenticação em duas etapas.',
    ],
    answer: 1,
  },
  {
    id: 'm2-q007',
    moduleId: 'm2',
    difficulty: 'basic',
    topic: 'privacidade',
    question: 'Qual conduta está mais alinhada com a proteção da privacidade?',
    options: [
      'Publicar dados pessoais sempre que solicitados.',
      'Fornecer apenas os dados necessários e revisar configurações de exposição.',
      'Aceitar qualquer pedido de permissão de aplicativos.',
      'Usar redes sociais como repositório de documentos pessoais.',
    ],
    answer: 1,
  },
  {
    id: 'm2-q008',
    moduleId: 'm2',
    difficulty: 'basic',
    topic: 'permissoes',
    question: 'Por que é importante revisar permissões de aplicativos?',
    options: [
      'Porque aplicativos podem solicitar acesso desnecessário a câmera, microfone, localização, contatos, fotos e arquivos.',
      'Porque permissões sempre deixam o dispositivo mais rápido.',
      'Porque permissões impedem o uso de autenticação em duas etapas.',
      'Porque todos os aplicativos oficiais precisam acessar todos os dados do usuário.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q009',
    moduleId: 'm2',
    difficulty: 'basic',
    topic: 'atualizacoes',
    question: 'Qual é uma razão importante para manter sistemas e aplicativos atualizados?',
    options: [
      'Atualizações servem apenas para mudar o visual do aplicativo.',
      'Atualizações podem corrigir vulnerabilidades exploradas por criminosos.',
      'Atualizações eliminam a necessidade de backup.',
      'Atualizações tornam senhas desnecessárias.',
    ],
    answer: 1,
  },
  {
    id: 'm2-q010',
    moduleId: 'm2',
    difficulty: 'basic',
    topic: 'dados-minimos',
    question: 'O que significa fornecer apenas os dados necessários em cadastros digitais?',
    options: [
      'Preencher todos os campos, inclusive os opcionais.',
      'Informar somente dados indispensáveis para a finalidade do serviço.',
      'Usar dados falsos em qualquer situação, inclusive em serviços públicos.',
      'Publicar os mesmos dados nas redes sociais para conferência.',
    ],
    answer: 1,
  },

  {
    id: 'm2-q011',
    moduleId: 'm2',
    difficulty: 'intermediate',
    topic: 'gerenciador-senhas',
    question: 'Qual é a vantagem principal de um gerenciador de senhas bem utilizado?',
    options: [
      'Permitir criar e guardar senhas fortes e únicas sem depender apenas da memória.',
      'Eliminar a necessidade de proteger a conta principal do gerenciador.',
      'Compartilhar automaticamente senhas com contatos confiáveis.',
      'Impedir todos os tipos de fraude financeira.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q012',
    moduleId: 'm2',
    difficulty: 'intermediate',
    topic: '2fa-metodos',
    question: 'Qual alternativa apresenta uma forma mais segura de 2FA do que SMS, quando disponível?',
    options: [
      'Receber códigos por mensagem de texto em qualquer chip.',
      'Usar aplicativo autenticador, chave física de segurança ou passkey.',
      'Anotar o código de 2FA em rede social privada.',
      'Enviar o código para si mesmo por aplicativo de mensagem.',
    ],
    answer: 1,
  },
  {
    id: 'm2-q013',
    moduleId: 'm2',
    difficulty: 'intermediate',
    topic: 'codigo-autenticacao',
    question: 'Por que códigos de autenticação não devem ser informados a terceiros?',
    options: [
      'Porque eles podem autorizar login, redefinição de senha ou operação sensível em nome do usuário.',
      'Porque códigos de autenticação só servem para publicidade.',
      'Porque códigos são públicos e não têm valor de segurança.',
      'Porque informar o código sempre bloqueia automaticamente a conta.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q014',
    moduleId: 'm2',
    difficulty: 'intermediate',
    topic: 'email-conta-mestra',
    question: 'Uma pessoa protege bancos com senha forte, mas mantém o e-mail sem 2FA e com senha repetida. Qual é o principal risco?',
    options: [
      'O e-mail frágil pode permitir redefinir senhas e acessar outros serviços.',
      'O banco ficará automaticamente mais protegido.',
      'A falta de 2FA no e-mail não tem impacto em outras contas.',
      'O único risco é receber mensagens promocionais.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q015',
    moduleId: 'm2',
    difficulty: 'intermediate',
    topic: 'backup-321',
    question: 'Qual estratégia de backup é mais resiliente?',
    options: [
      'Manter apenas uma cópia no mesmo computador.',
      'Salvar tudo em uma única pasta sincronizada sem conferência.',
      'Ter mais de uma cópia, em locais diferentes, com ao menos uma alternativa protegida contra perda ou comprometimento.',
      'Confiar apenas na memória do usuário para reconstruir arquivos.',
    ],
    answer: 2,
  },
  {
    id: 'm2-q016',
    moduleId: 'm2',
    difficulty: 'intermediate',
    topic: 'ransomware',
    question: 'Por que backup é especialmente importante diante de ransomware?',
    options: [
      'Porque ransomware sempre é removido apenas trocando a senha.',
      'Porque cópias confiáveis podem permitir recuperação sem depender do criminoso.',
      'Porque backup impede que qualquer malware seja instalado.',
      'Porque ransomware só afeta arquivos sem valor.',
    ],
    answer: 1,
  },
  {
    id: 'm2-q017',
    moduleId: 'm2',
    difficulty: 'intermediate',
    topic: 'teste-backup',
    question: 'Por que é recomendável testar a restauração de backups?',
    options: [
      'Porque backup não testado pode falhar justamente quando for necessário.',
      'Porque testar backup apaga os arquivos originais.',
      'Porque backups só funcionam quando ficam públicos.',
      'Porque restauração é desnecessária em incidentes digitais.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q018',
    moduleId: 'm2',
    difficulty: 'intermediate',
    topic: 'permissoes',
    question: 'Um aplicativo de lanterna solicita acesso a contatos, localização, microfone e fotos. Qual análise é mais adequada?',
    options: [
      'As permissões parecem excessivas para a finalidade informada e devem ser avaliadas criticamente.',
      'Todo aplicativo precisa de todas as permissões para funcionar.',
      'Permissões excessivas aumentam a privacidade.',
      'Aplicativos simples nunca podem coletar dados.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q019',
    moduleId: 'm2',
    difficulty: 'intermediate',
    topic: 'cookies-rastreamento',
    question: 'Qual atitude reduz exposição em sites que pedem consentimento para cookies e rastreamento?',
    options: [
      'Aceitar todas as opções automaticamente.',
      'Revisar preferências e recusar o que não for necessário quando possível.',
      'Informar dados pessoais adicionais para melhorar a navegação.',
      'Usar a mesma senha no aviso de cookies.',
    ],
    answer: 1,
  },
  {
    id: 'm2-q020',
    moduleId: 'm2',
    difficulty: 'intermediate',
    topic: 'exposicao-redes',
    question: 'Como a exposição excessiva em redes sociais pode aumentar o risco de golpe?',
    options: [
      'Dados sobre rotina, família, viagens e preferências podem ser usados para golpes personalizados.',
      'Exposição excessiva impede engenharia social.',
      'Golpistas não observam redes sociais.',
      'Quanto mais dados públicos, menor o risco de fraude.',
    ],
    answer: 0,
  },

  {
    id: 'm2-q021',
    moduleId: 'm2',
    difficulty: 'advanced',
    topic: 'caso-integrado',
    question: 'Uma pessoa usa senha repetida em loja online, e-mail e rede social. A loja sofre vazamento. Qual risco é mais relevante?',
    options: [
      'O vazamento pode permitir tentativa de acesso a outras contas por reutilização da mesma senha.',
      'O risco fica restrito ao histórico de compras da loja.',
      'O e-mail fica automaticamente protegido pelo vazamento.',
      'A troca de senha é desnecessária se a loja for conhecida.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q022',
    moduleId: 'm2',
    difficulty: 'advanced',
    topic: 'resposta-conta-invadida',
    question: 'Ao receber alerta de login suspeito em uma conta crítica, qual sequência é mais adequada?',
    options: [
      'Ignorar o alerta e aguardar novo aviso.',
      'Trocar a senha por uma única senha já usada em outro serviço.',
      'Negar ou encerrar sessões suspeitas, trocar senha, ativar ou revisar 2FA e verificar dados de recuperação.',
      'Publicar o alerta em redes sociais com detalhes da conta.',
    ],
    answer: 2,
  },
  {
    id: 'm2-q023',
    moduleId: 'm2',
    difficulty: 'advanced',
    topic: 'passkeys',
    question: 'Qual afirmação sobre passkeys é mais adequada para fins de higiene digital?',
    options: [
      'Passkeys podem reduzir dependência de senhas e aumentar resistência a phishing, quando oferecidas pelo serviço e configuradas corretamente.',
      'Passkeys dispensam qualquer cuidado com dispositivos.',
      'Passkeys tornam backups desnecessários.',
      'Passkeys só funcionam em redes sociais públicas.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q024',
    moduleId: 'm2',
    difficulty: 'advanced',
    topic: 'backup-contaminado',
    question: 'Qual risco existe quando o único backup fica sempre conectado ao computador principal?',
    options: [
      'Ele pode ser afetado por falha, exclusão indevida ou malware que comprometa os arquivos acessíveis.',
      'Ele se torna automaticamente imune a ransomware.',
      'Ele passa a substituir atualizações de segurança.',
      'Ele impede qualquer vazamento de dados.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q025',
    moduleId: 'm2',
    difficulty: 'advanced',
    topic: 'minimizacao-dados',
    question: 'Por que a minimização de dados reduz riscos?',
    options: [
      'Porque quanto menos dados desnecessários forem coletados e expostos, menor o material disponível para abuso, fraude ou golpe direcionado.',
      'Porque dados minimizados tornam senhas desnecessárias.',
      'Porque minimização impede todo tipo de vazamento.',
      'Porque serviços digitais só funcionam se o usuário fornecer dados excessivos.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q026',
    moduleId: 'm2',
    difficulty: 'advanced',
    topic: 'lgpd-finalidade',
    question: 'Qual relação há entre proteção de dados e finalidade do tratamento?',
    options: [
      'Dados devem ser coletados e usados de modo compatível com finalidade legítima, específica e informada.',
      'Dados podem ser coletados sem finalidade sempre que houver curiosidade comercial.',
      'Finalidade só importa para órgãos públicos, nunca para empresas.',
      'Quanto mais genérica a finalidade, maior a segurança.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q027',
    moduleId: 'm2',
    difficulty: 'advanced',
    topic: 'conta-recuperacao',
    question: 'Por que manter dados de recuperação atualizados é parte da higiene digital?',
    options: [
      'Porque e-mail e telefone de recuperação ajudam a retomar acesso legítimo e impedir sequestro definitivo da conta.',
      'Porque dados de recuperação devem ser públicos.',
      'Porque recuperação de conta substitui 2FA.',
      'Porque dados desatualizados aumentam a segurança.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q028',
    moduleId: 'm2',
    difficulty: 'advanced',
    topic: 'risco-composto',
    question: 'Qual cenário apresenta risco composto mais grave?',
    options: [
      'Senha única, 2FA ativo, backup testado e permissões revisadas.',
      'Senha repetida, e-mail sem 2FA, backup inexistente e muita exposição pública de dados pessoais.',
      'Backup automático com conferência periódica e poucos dados públicos.',
      'Aplicativos atualizados e permissões restritas.',
    ],
    answer: 1,
  },
  {
    id: 'm2-q029',
    moduleId: 'm2',
    difficulty: 'advanced',
    topic: 'higiene-rotina',
    question: 'Qual afirmação sintetiza melhor a ideia de higiene digital como rotina?',
    options: [
      'É uma sequência de hábitos permanentes que reduz a superfície de ataque e melhora a capacidade de recuperação.',
      'É uma ação única feita depois de sofrer golpe.',
      'É um conjunto de dicas opcionais sem impacto prático.',
      'É apenas a instalação inicial de um aplicativo de segurança.',
    ],
    answer: 0,
  },
  {
    id: 'm2-q030',
    moduleId: 'm2',
    difficulty: 'advanced',
    topic: 'decisao-pratica',
    question: 'Uma pessoa quer melhorar a segurança em uma tarde. Qual plano inicial é mais consistente?',
    options: [
      'Trocar todas as senhas por uma única senha forte, desativar 2FA e apagar backups.',
      'Ativar 2FA no e-mail e bancos, trocar senhas repetidas, configurar gerenciador, revisar permissões e criar backup automático testável.',
      'Publicar nas redes que está protegida e compartilhar dicas com todos os contatos.',
      'Instalar qualquer aplicativo indicado em anúncio patrocinado.',
    ],
    answer: 1,
  },
]