export const module3Questions = [
  {
    id: 'm3-q001',
    moduleId: 'm3',
    difficulty: 'basic',
    topic: 'dispositivos',
    question: 'Qual alternativa resume melhor a importância de proteger dispositivos e redes?',
    options: [
      'Dispositivos e redes são apenas acessórios, sem relação com contas e dados.',
      'Celulares, computadores e roteadores são pontos de acesso à vida digital e podem ser explorados para acessar dados, contas e serviços.',
      'A proteção técnica só importa para empresas de tecnologia.',
      'A segurança depende apenas de senhas fortes, independentemente do dispositivo usado.',
    ],
    answer: 1,
  },
  {
    id: 'm3-q002',
    moduleId: 'm3',
    difficulty: 'basic',
    topic: 'atualizacoes',
    question: 'Por que manter sistemas e aplicativos atualizados é uma medida essencial?',
    options: [
      'Porque atualizações corrigem vulnerabilidades que podem ser exploradas por atacantes ou malware.',
      'Porque atualizações substituem backup e autenticação forte.',
      'Porque atualizações servem apenas para alterar aparência dos aplicativos.',
      'Porque sistemas desatualizados são sempre mais rápidos e seguros.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q003',
    moduleId: 'm3',
    difficulty: 'basic',
    topic: 'apps-oficiais',
    question: 'Qual é a prática mais segura ao instalar aplicativos?',
    options: [
      'Instalar aplicativos recebidos por link em mensagens.',
      'Usar apenas lojas oficiais e conferir nome do aplicativo e desenvolvedor.',
      'Instalar versões modificadas para desbloquear recursos pagos.',
      'Confiar em qualquer anúncio patrocinado.',
    ],
    answer: 1,
  },
  {
    id: 'm3-q004',
    moduleId: 'm3',
    difficulty: 'basic',
    topic: 'bloqueio-tela',
    question: 'Por que o bloqueio de tela do celular deve ser forte?',
    options: [
      'Porque uma senha fraca ou aparelho desbloqueado pode permitir acesso a mensagens, apps, contas e configurações.',
      'Porque o bloqueio de tela serve apenas para economizar bateria.',
      'Porque biometria elimina qualquer necessidade de senha.',
      'Porque o bloqueio de tela impede todos os golpes por telefone.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q005',
    moduleId: 'm3',
    difficulty: 'basic',
    topic: 'chip-sim',
    question: 'Por que proteger o chip SIM com PIN pode reduzir riscos?',
    options: [
      'Porque impede que outra pessoa use a linha em outro aparelho para receber SMS de verificação.',
      'Porque aumenta automaticamente a velocidade da internet móvel.',
      'Porque substitui senhas fortes nos aplicativos.',
      'Porque bloqueia qualquer tentativa de phishing.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q006',
    moduleId: 'm3',
    difficulty: 'basic',
    topic: 'roteador',
    question: 'Qual medida deve ser tomada em relação à senha administrativa do roteador?',
    options: [
      'Manter a senha padrão de fábrica para facilitar suporte.',
      'Trocar a senha padrão por senha forte e guardá-la em local seguro.',
      'Usar o nome da operadora como senha.',
      'Compartilhar a senha administrativa com todos os visitantes.',
    ],
    answer: 1,
  },
  {
    id: 'm3-q007',
    moduleId: 'm3',
    difficulty: 'basic',
    topic: 'wifi',
    question: 'Qual configuração é mais segura para a rede Wi-Fi doméstica?',
    options: [
      'WEP com senha curta.',
      'Rede aberta para facilitar conexão.',
      'WPA2/WPA3 ou WPA3, com senha forte.',
      'Nome da rede igual ao modelo do roteador e senha padrão.',
    ],
    answer: 2,
  },
  {
    id: 'm3-q008',
    moduleId: 'm3',
    difficulty: 'basic',
    topic: 'antimalware',
    question: 'Qual é a função de ferramentas antimalware?',
    options: [
      'Ajudar a detectar, prevenir ou remover códigos maliciosos.',
      'Garantir que qualquer link recebido seja seguro.',
      'Substituir atualizações do sistema.',
      'Eliminar a necessidade de cuidado com anexos.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q009',
    moduleId: 'm3',
    difficulty: 'basic',
    topic: 'firewall',
    question: 'Para que serve o firewall pessoal?',
    options: [
      'Para bloquear conexões não autorizadas e reduzir ataques vindos pela rede.',
      'Para guardar senhas de banco.',
      'Para acelerar compras online.',
      'Para apagar automaticamente mensagens suspeitas.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q010',
    moduleId: 'm3',
    difficulty: 'basic',
    topic: 'trabalho-remoto',
    question: 'No trabalho remoto, qual conduta é mais adequada?',
    options: [
      'Compartilhar credenciais com familiares para facilitar tarefas.',
      'Usar canais oficiais, respeitar regras da organização e não burlar mecanismos de segurança.',
      'Misturar livremente contas pessoais e profissionais.',
      'Instalar qualquer programa que facilite o trabalho, sem autorização.',
    ],
    answer: 1,
  },

  {
    id: 'm3-q011',
    moduleId: 'm3',
    difficulty: 'intermediate',
    topic: 'celular-carteira',
    question: 'Por que o celular deve ser tratado como uma espécie de carteira digital?',
    options: [
      'Porque concentra banco, e-mail, mensagens, autenticação, documentos, fotos, nuvem e canais de recuperação de contas.',
      'Porque serve apenas para chamadas e redes sociais.',
      'Porque não contém informações úteis para criminosos.',
      'Porque a operadora sempre consegue impedir prejuízos automaticamente.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q012',
    moduleId: 'm3',
    difficulty: 'intermediate',
    topic: 'tela-bloqueada',
    question: 'Qual risco existe em permitir visualização de mensagens e atalhos de configuração na tela bloqueada?',
    options: [
      'Pode facilitar acesso a códigos, mensagens sensíveis e alterações que dificultem localização ou proteção do aparelho.',
      'Impede totalmente o furto do aparelho.',
      'Aumenta a privacidade e dificulta ações indevidas.',
      'Permite que o backup seja feito com mais segurança.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q013',
    moduleId: 'm3',
    difficulty: 'intermediate',
    topic: 'aplicativos-sensiveis',
    question: 'Qual medida ajuda a reduzir danos se alguém obtiver acesso físico ao celular?',
    options: [
      'Deixar todos os aplicativos abertos para facilitar acesso.',
      'Bloquear ou proteger aplicativos sensíveis com biometria, senha ou recurso nativo do sistema.',
      'Salvar senhas bancárias em bloco de notas.',
      'Desativar bloqueio automático de tela.',
    ],
    answer: 1,
  },
  {
    id: 'm3-q014',
    moduleId: 'm3',
    difficulty: 'intermediate',
    topic: 'imei',
    question: 'Por que é útil anotar e guardar o IMEI do aparelho?',
    options: [
      'Porque o IMEI pode ser necessário para bloqueio na operadora e registro de ocorrência em caso de furto.',
      'Porque o IMEI substitui a senha de desbloqueio.',
      'Porque o IMEI impede qualquer instalação de aplicativo falso.',
      'Porque o IMEI deve ser publicado nas redes sociais.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q015',
    moduleId: 'm3',
    difficulty: 'intermediate',
    topic: 'programas-originais',
    question: 'Por que programas não originais aumentam o risco de segurança?',
    options: [
      'Porque podem conter malware, não receber atualizações, funcionar incorretamente ou não ter suporte.',
      'Porque são sempre mais seguros do que versões oficiais.',
      'Porque dispensam antivírus e firewall.',
      'Porque impedem ataques de engenharia social.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q016',
    moduleId: 'm3',
    difficulty: 'intermediate',
    topic: 'aplicativos-desnecessarios',
    question: 'Por que remover aplicativos que não são mais usados é uma boa prática?',
    options: [
      'Porque reduz a superfície de ataque e facilita manter o restante atualizado.',
      'Porque aumenta a exposição de dados pessoais.',
      'Porque aplicativos antigos sempre protegem o dispositivo.',
      'Porque impede que o usuário use autenticação forte.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q017',
    moduleId: 'm3',
    difficulty: 'intermediate',
    topic: 'roteador-ssid',
    question: 'Por que trocar o nome padrão da rede Wi-Fi pode melhorar a segurança?',
    options: [
      'Porque nomes padrão podem revelar informações sobre equipamento, provedor ou vulnerabilidades conhecidas.',
      'Porque o nome da rede substitui a senha do Wi-Fi.',
      'Porque redes com nome padrão não precisam de criptografia.',
      'Porque nomes personalizados impedem qualquer malware.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q018',
    moduleId: 'm3',
    difficulty: 'intermediate',
    topic: 'roteador-atualizacao',
    question: 'Por que roteadores também precisam de atualização?',
    options: [
      'Porque equipamentos de rede podem ter vulnerabilidades exploradas para alterar configurações, instalar malware ou interceptar tráfego.',
      'Porque roteadores atualizados dispensam senha.',
      'Porque atualização do roteador apaga todos os dados pessoais.',
      'Porque redes Wi-Fi não sofrem ataques.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q019',
    moduleId: 'm3',
    difficulty: 'intermediate',
    topic: 'wifi-publico',
    question: 'Qual conduta é mais segura ao usar Wi-Fi público?',
    options: [
      'Realizar transações sensíveis sem verificar a rede.',
      'Evitar operações sensíveis, preferir conexão móvel ou VPN confiável quando aplicável e confirmar se a rede é legítima.',
      'Desativar HTTPS para facilitar navegação.',
      'Conectar-se automaticamente a qualquer rede aberta com nome conhecido.',
    ],
    answer: 1,
  },
  {
    id: 'm3-q020',
    moduleId: 'm3',
    difficulty: 'intermediate',
    topic: 'trabalho-remoto',
    question: 'Por que é recomendável separar uso pessoal e profissional no trabalho remoto?',
    options: [
      'Porque instalar apps pessoais, navegar em sites diversos ou compartilhar o computador pode introduzir vulnerabilidades e comprometer dados corporativos.',
      'Porque equipamentos corporativos devem ser usados por toda a família.',
      'Porque a separação impede qualquer necessidade de atualização.',
      'Porque contas pessoais são sempre mais seguras do que contas corporativas.',
    ],
    answer: 0,
  },

  {
    id: 'm3-q021',
    moduleId: 'm3',
    difficulty: 'advanced',
    topic: 'caso-integrado',
    question: 'Uma pessoa recebe link de suposto suporte técnico e instala aplicativo fora da loja oficial em celular usado para banco e e-mail. Qual análise é mais adequada?',
    options: [
      'O risco envolve engenharia social, instalação indevida, possível malware, acesso a contas e comprometimento de dados sensíveis.',
      'O risco é inexistente se o aplicativo tiver ícone profissional.',
      'O problema se limita ao consumo de bateria.',
      'A instalação fora da loja oficial é recomendada em situações urgentes.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q022',
    moduleId: 'm3',
    difficulty: 'advanced',
    topic: 'furto-celular',
    question: 'Qual conjunto de medidas reduz melhor os danos antes de um possível furto de celular?',
    options: [
      'Senha forte de tela, bloqueio automático, proteção de apps sensíveis, PIN do chip SIM, localização remota, backup e IMEI anotado.',
      'Tela sem senha, chip sem PIN e senhas salvas em notas.',
      'Aplicativos bancários abertos e notificações sensíveis visíveis na tela bloqueada.',
      'Uso exclusivo de biometria sem qualquer senha forte de reserva.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q023',
    moduleId: 'm3',
    difficulty: 'advanced',
    topic: 'rede-domestica',
    question: 'Qual configuração de rede doméstica é mais coerente com boas práticas?',
    options: [
      'Senha administrativa padrão, Wi-Fi aberto e WEP.',
      'Senha administrativa forte, senha Wi-Fi forte, SSID sem dados pessoais, WPA2/WPA3 ou WPA3 e roteador atualizado.',
      'Nome da rede com endereço da residência e modelo do roteador.',
      'Senha curta compartilhada com todos os visitantes e sem rede de convidados.',
    ],
    answer: 1,
  },
  {
    id: 'm3-q024',
    moduleId: 'm3',
    difficulty: 'advanced',
    topic: 'malware',
    question: 'Qual sequência é mais adequada diante de arquivo anexo inesperado recebido por e-mail?',
    options: [
      'Abrir rapidamente, porque anexos enviados por e-mail são sempre verificados.',
      'Analisar contexto, desconfiar, verificar por outro canal, usar antimalware quando cabível e não abrir em caso de dúvida.',
      'Encaminhar para contatos testarem primeiro.',
      'Desativar antivírus para evitar bloqueio indevido.',
    ],
    answer: 1,
  },
  {
    id: 'm3-q025',
    moduleId: 'm3',
    difficulty: 'advanced',
    topic: 'vulnerabilidade',
    question: 'Qual afirmação descreve melhor uma vulnerabilidade?',
    options: [
      'Falha de projeto, implementação ou configuração que pode ser explorada para comprometer sistemas, dispositivos ou dados.',
      'Recurso opcional sem impacto em segurança.',
      'Senha longa usada em várias contas.',
      'Qualquer mensagem recebida por aplicativo.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q026',
    moduleId: 'm3',
    difficulty: 'advanced',
    topic: 'criptografia',
    question: 'Por que a criptografia de disco é relevante em computadores e dispositivos de trabalho?',
    options: [
      'Porque protege dados armazenados contra acesso indevido em caso de perda, furto ou acesso físico não autorizado.',
      'Porque impede todo tipo de phishing.',
      'Porque substitui backup e autenticação.',
      'Porque torna desnecessário bloquear a tela.',
    ],
    answer: 0,
  },
  {
    id: 'm3-q027',
    moduleId: 'm3',
    difficulty: 'advanced',
    topic: 'trabalho-remoto',
    question: 'No contexto de trabalho remoto, qual cenário representa maior risco?',
    options: [
      'Computador atualizado, VPN institucional quando exigida, autenticação forte e uso apenas de apps autorizados.',
      'Computador corporativo usado por familiares, apps não autorizados, credenciais compartilhadas e tentativa de burlar controles de segurança.',
      'Separação entre contas pessoais e profissionais.',
      'Backup, antimalware e firewall ativos.',
    ],
    answer: 1,
  },
  {
    id: 'm3-q028',
    moduleId: 'm3',
    difficulty: 'advanced',
    topic: 'resposta-dispositivo-comprometido',
    question: 'Ao suspeitar que um dispositivo foi infectado por malware, qual resposta inicial é mais adequada?',
    options: [
      'Continuar usando normalmente para observar o comportamento.',
      'Desconectar quando cabível, evitar novas operações sensíveis, buscar verificação técnica, trocar senhas a partir de dispositivo confiável e revisar contas afetadas.',
      'Informar senhas ao suposto suporte recebido por mensagem.',
      'Instalar mais aplicativos desconhecidos para testar.',
    ],
    answer: 1,
  },
  {
    id: 'm3-q029',
    moduleId: 'm3',
    difficulty: 'advanced',
    topic: 'risco-composto',
    question: 'Qual cenário apresenta risco composto mais grave?',
    options: [
      'Celular atualizado, senha forte, apps oficiais, PIN no SIM e backup ativo.',
      'Celular sem bloqueio forte, apps fora da loja, chip sem PIN, Wi-Fi inseguro e roteador com senha padrão.',
      'Computador com firewall ativo e sistema atualizado.',
      'Roteador atualizado com WPA3 e senha forte.',
    ],
    answer: 1,
  },
  {
    id: 'm3-q030',
    moduleId: 'm3',
    difficulty: 'advanced',
    topic: 'sintese',
    question: 'Qual alternativa sintetiza melhor o aprendizado esperado no Módulo 3?',
    options: [
      'Proteger dispositivos e redes é parte essencial da prevenção, porque contas, dados, autenticação e transações dependem desse ambiente técnico.',
      'Dispositivos não influenciam a segurança das contas.',
      'A rede Wi-Fi doméstica não precisa de cuidado se o usuário tiver senha no e-mail.',
      'Trabalho remoto seguro depende apenas da boa vontade do usuário.',
    ],
    answer: 0,
  },
]