export const module1Questions = [
  {
    id: 'm1-q001',
    moduleId: 'm1',
    difficulty: 'basic',
    topic: 'cidadania-digital',
    question: 'Qual alternativa expressa melhor a ideia de segurança digital como cidadania?',
    options: [
      'É uma prática restrita a especialistas em tecnologia e investigação criminal.',
      'É o conjunto de hábitos, responsabilidades e decisões que permite usar serviços digitais com mais consciência, proteção e capacidade de reação.',
      'É uma obrigação exclusiva dos bancos, plataformas digitais e órgãos públicos.',
      'É apenas a instalação de antivírus e aplicativos de bloqueio no celular.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q002',
    moduleId: 'm1',
    difficulty: 'basic',
    topic: 'responsabilidade-compartilhada',
    question: 'Por que a segurança digital deve ser compreendida como responsabilidade compartilhada?',
    options: [
      'Porque golpes digitais envolvem instituições públicas, setor privado, plataformas, tecnologia e comportamento do usuário.',
      'Porque apenas o cidadão pode impedir crimes digitais.',
      'Porque a investigação criminal substitui medidas preventivas.',
      'Porque bancos e plataformas não têm qualquer papel na prevenção.',
    ],
    answer: 0,
  },
  {
    id: 'm1-q003',
    moduleId: 'm1',
    difficulty: 'basic',
    topic: 'engenharia-social',
    question: 'Qual situação representa melhor um exemplo de engenharia social?',
    options: [
      'Atualizar o sistema operacional por meio da loja oficial.',
      'Receber uma ligação que simula uma central bancária e induz a vítima a informar um código de autenticação.',
      'Configurar autenticação em duas etapas em uma conta de e-mail.',
      'Digitar diretamente o endereço oficial de um banco no navegador.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q004',
    moduleId: 'm1',
    difficulty: 'basic',
    topic: 'sinais-de-alerta',
    question: 'Qual conjunto de sinais deve levar o cidadão a interromper a interação e verificar o fato por canal oficial?',
    options: [
      'Mensagem sem urgência, orientação para buscar o site oficial e ausência de pedido de dados sensíveis.',
      'Pedido de senha ou código, ameaça de bloqueio, link externo, sigilo e pressão para decisão imediata.',
      'Informação educativa publicada em canal institucional conhecido.',
      'Solicitação para revisar configurações diretamente no aplicativo oficial já instalado.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q005',
    moduleId: 'm1',
    difficulty: 'basic',
    topic: 'canais-oficiais',
    question: 'Diante de mensagem urgente com link para regularizar uma conta bancária, qual é a atitude mais segura?',
    options: [
      'Clicar no link rapidamente antes do prazo terminar.',
      'Responder à mensagem pedindo mais detalhes.',
      'Acessar o banco por aplicativo oficial ou canal conhecido, sem usar o link recebido.',
      'Encaminhar a mensagem para outros contatos verificarem.',
    ],
    answer: 2,
  },
  {
    id: 'm1-q006',
    moduleId: 'm1',
    difficulty: 'basic',
    topic: 'tríade-do-curso',
    question: 'Qual é a tríade central adotada no curso?',
    options: [
      'Comprar, vender e compartilhar.',
      'Identificar o risco, prevenir com método e reagir com segurança.',
      'Instalar, configurar e programar.',
      'Denunciar, punir e bloquear.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q007',
    moduleId: 'm1',
    difficulty: 'basic',
    topic: 'preservacao-evidencias',
    question: 'Por que preservar mensagens, números, links, perfis e comprovantes pode ser importante?',
    options: [
      'Porque isso garante automaticamente a recuperação do dinheiro.',
      'Porque substitui a necessidade de procurar canais oficiais.',
      'Porque pode ajudar na comunicação do fato, no atendimento da instituição envolvida e em eventual apuração.',
      'Porque permite que a vítima investigue e confronte diretamente o suspeito.',
    ],
    answer: 2,
  },
  {
    id: 'm1-q008',
    moduleId: 'm1',
    difficulty: 'basic',
    topic: 'papel-cidadao',
    question: 'Qual conduta representa melhor o papel do cidadão na primeira resposta a uma tentativa de golpe?',
    options: [
      'Tentar identificar o criminoso por conta própria.',
      'Interromper o contato, não fornecer novos dados, preservar evidências e buscar canais oficiais.',
      'Apagar todas as mensagens para evitar constrangimento.',
      'Continuar a conversa para obter mais informações do golpista.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q009',
    moduleId: 'm1',
    difficulty: 'basic',
    topic: 'falsa-central',
    question: 'Em uma falsa central bancária, qual pedido deve ser tratado como forte sinal de alerta?',
    options: [
      'Orientação para procurar o número oficial no cartão ou aplicativo.',
      'Pedido para aguardar atendimento presencial.',
      'Solicitação de código recebido por SMS, senha ou instalação de aplicativo remoto.',
      'Informação genérica sobre segurança publicada no site oficial.',
    ],
    answer: 2,
  },
  {
    id: 'm1-q010',
    moduleId: 'm1',
    difficulty: 'basic',
    topic: 'prevenção',
    question: 'Qual afirmação está mais alinhada com a lógica preventiva do curso?',
    options: [
      'A prevenção só começa depois que o prejuízo ocorre.',
      'A prevenção depende apenas de tecnologia sofisticada.',
      'A prevenção combina informação, hábitos seguros, verificação independente e resposta organizada.',
      'A prevenção é inútil diante de golpes digitais.',
    ],
    answer: 2,
  },

  {
    id: 'm1-q011',
    moduleId: 'm1',
    difficulty: 'intermediate',
    topic: 'instituicoes',
    question: 'O papel da Polícia Federal, no contexto do módulo, deve ser compreendido principalmente como:',
    options: [
      'Substituir bancos e plataformas em todo atendimento inicial ao consumidor.',
      'Prestar consultoria privada de segurança digital para cada usuário individual.',
      'Exercer função investigativa dentro de sua esfera de atribuição, especialmente quando houver competência legal, dimensão federal, interestadual ou internacional.',
      'Bloquear imediatamente qualquer perfil ou anúncio suspeito, sem necessidade de procedimento ou cooperação.',
    ],
    answer: 2,
  },
  {
    id: 'm1-q012',
    moduleId: 'm1',
    difficulty: 'intermediate',
    topic: 'instituicoes',
    question: 'O papel do MJSP no ecossistema de prevenção e enfrentamento a fraudes digitais está mais associado a:',
    options: [
      'Articulação estratégica, coordenação de políticas públicas e integração de atores públicos e privados.',
      'Emissão direta de cartões, senhas e códigos de autenticação bancária.',
      'Atendimento comercial de aplicativos financeiros.',
      'Fornecimento de antivírus oficial para todos os cidadãos.',
    ],
    answer: 0,
  },
  {
    id: 'm1-q013',
    moduleId: 'm1',
    difficulty: 'intermediate',
    topic: 'instituicoes',
    question: 'A atuação da FEBRABAN, no contexto deste curso, é melhor descrita como:',
    options: [
      'Órgão de polícia judiciária com atribuição criminal direta.',
      'Entidade representativa do setor bancário, com papel relevante na prevenção setorial, comunicação antifraude e difusão de boas práticas de segurança financeira.',
      'Autoridade judicial responsável por condenar autores de fraudes bancárias digitais.',
      'Plataforma pública obrigatória para registro de boletins de ocorrência.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q014',
    moduleId: 'm1',
    difficulty: 'intermediate',
    topic: 'fraude-golpe',
    question: 'Qual distinção é mais adequada entre fraude e golpe no contexto de transações digitais?',
    options: [
      'Fraude e golpe são sempre sinônimos absolutos e não há utilidade em diferenciá-los.',
      'Na fraude, em sentido operacional, pode haver movimentação irregular sem atuação consciente do titular; no golpe, a vítima é induzida por engenharia social a praticar o ato.',
      'No golpe, sempre há invasão técnica do dispositivo; na fraude, sempre há ameaça física.',
      'A fraude só ocorre presencialmente, enquanto o golpe só ocorre em redes sociais.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q015',
    moduleId: 'm1',
    difficulty: 'intermediate',
    topic: 'ecossistema',
    question: 'Qual alternativa descreve melhor o ecossistema de segurança digital?',
    options: [
      'Um sistema em que apenas o usuário é responsável por evitar crimes.',
      'Uma atuação compartilhada entre instituições públicas, setor privado, plataformas, comunidade e cidadãos.',
      'Uma área limitada a especialistas em programação.',
      'Um conjunto de medidas que só importa depois do prejuízo.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q016',
    moduleId: 'm1',
    difficulty: 'intermediate',
    topic: 'alianca',
    question: 'Por que iniciativas de cooperação público-privada são relevantes no enfrentamento a fraudes digitais?',
    options: [
      'Porque todos os golpes digitais ocorrem dentro de uma única instituição.',
      'Porque fraudes podem envolver redes sociais, telefonia, bancos, plataformas, contas receptoras, dados pessoais e atuação criminosa coordenada.',
      'Porque a cooperação elimina a necessidade de prevenção individual.',
      'Porque apenas campanhas publicitárias são suficientes para impedir fraudes digitais.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q017',
    moduleId: 'm1',
    difficulty: 'intermediate',
    topic: 'classificacao',
    question: 'Por que a imagem do “hacker invasor” é insuficiente para compreender os crimes cibernéticos atuais?',
    options: [
      'Porque todos os crimes digitais são cometidos sem tecnologia.',
      'Porque muitos crimes digitais usam engenharia social, falsas identidades, páginas fraudulentas, dados vazados e manipulação da confiança.',
      'Porque crimes digitais são sempre praticados por pessoas conhecidas da vítima.',
      'Porque invasões técnicas deixaram de existir.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q018',
    moduleId: 'm1',
    difficulty: 'intermediate',
    topic: 'primeira-resposta',
    question: 'Após perceber que informou parcialmente dados a uma falsa central, qual sequência é mais adequada?',
    options: [
      'Apagar a conversa, bloquear todos os contatos e aguardar.',
      'Continuar conversando para descobrir quem é o suspeito.',
      'Interromper o contato, procurar a instituição por canal oficial, preservar registros e adotar medidas de contenção.',
      'Compartilhar a situação em grupos públicos com todos os dados do caso.',
    ],
    answer: 2,
  },
  {
    id: 'm1-q019',
    moduleId: 'm1',
    difficulty: 'intermediate',
    topic: 'canais-oficiais',
    question: 'Por que “contato recebido não prova identidade” é uma regra importante?',
    options: [
      'Porque mensagens recebidas são tecnicamente impossíveis de falsificar.',
      'Porque golpistas podem simular nomes, logotipos, fotos, números, linguagem institucional e senso de urgência.',
      'Porque somente mensagens anônimas podem ser fraudulentas.',
      'Porque ligações telefônicas são sempre confiáveis.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q020',
    moduleId: 'm1',
    difficulty: 'intermediate',
    topic: 'prevenção-europa',
    question: 'Qual prática está mais alinhada com padrões internacionais de higiene digital?',
    options: [
      'Usar a mesma senha em todos os serviços para facilitar memorização.',
      'Ativar verificação em duas etapas, manter sistemas atualizados, desconfiar de links inesperados e fazer backup de dados importantes.',
      'Desativar atualizações automáticas para evitar mudanças no sistema.',
      'Abrir anexos rapidamente para não perder prazos.',
    ],
    answer: 1,
  },

  {
    id: 'm1-q021',
    moduleId: 'm1',
    difficulty: 'advanced',
    topic: 'caso-integrado',
    question: 'Uma pessoa recebe SMS com link para pagar taxa de encomenda, acessa página semelhante à oficial e informa dados de cartão. Qual análise é mais completa?',
    options: [
      'A aparência oficial da página confirma a legitimidade do serviço.',
      'Há possível phishing com uso de identidade visual falsa, coleta indevida de dados e necessidade de contato com a instituição financeira por canal oficial.',
      'O caso não exige nenhuma providência se o produto ainda não chegou.',
      'A melhor providência é responder ao SMS pedindo confirmação.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q022',
    moduleId: 'm1',
    difficulty: 'advanced',
    topic: 'caso-integrado',
    question: 'Um familiar envia mensagem dizendo que trocou de número e pede Pix urgente. Qual resposta demonstra melhor compreensão do módulo?',
    options: [
      'Transferir valor pequeno para testar se a conta é verdadeira.',
      'Pedir uma selfie pelo mesmo aplicativo e confiar se a foto parecer real.',
      'Confirmar por canal independente, preferencialmente ligação de voz ou vídeo para contato conhecido, antes de qualquer transferência.',
      'Enviar os dados bancários próprios para facilitar a identificação.',
    ],
    answer: 2,
  },
  {
    id: 'm1-q023',
    moduleId: 'm1',
    difficulty: 'advanced',
    topic: 'caso-integrado',
    question: 'Uma campanha pública orienta a população a não compartilhar códigos de autenticação. Qual é a função preventiva desse tipo de comunicação?',
    options: [
      'Substituir a investigação criminal em todos os casos.',
      'Reduzir a eficácia de golpes recorrentes ao ensinar padrões de risco antes do prejuízo.',
      'Permitir que cidadãos bloqueiem contas de terceiros sem procedimento.',
      'Garantir que nenhum golpe ocorra novamente.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q024',
    moduleId: 'm1',
    difficulty: 'advanced',
    topic: 'competencia',
    question: 'Por que o curso evita afirmar que toda fraude digital deve ser investigada pela Polícia Federal?',
    options: [
      'Porque a Polícia Federal não atua em crimes cibernéticos.',
      'Porque a atribuição investigativa depende de critérios legais, natureza do fato, competência e eventual dimensão federal, interestadual ou internacional.',
      'Porque fraudes digitais não são crimes.',
      'Porque apenas bancos podem investigar crimes contra clientes.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q025',
    moduleId: 'm1',
    difficulty: 'advanced',
    topic: 'tratamento-vitima',
    question: 'Por que o tratamento adequado da vítima é relevante na política de prevenção a golpes digitais?',
    options: [
      'Porque a vítima deve ser responsabilizada automaticamente por ter caído no golpe.',
      'Porque acolhimento, orientação e resposta rápida podem reduzir danos, melhorar registros e evitar revitimização.',
      'Porque o tratamento da vítima elimina a necessidade de preservar evidências.',
      'Porque a vítima deve sempre resolver o caso diretamente com o suspeito.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q026',
    moduleId: 'm1',
    difficulty: 'advanced',
    topic: 'analise-sinais',
    question: 'Qual combinação torna uma mensagem especialmente suspeita?',
    options: [
      'Informação educativa, ausência de link e orientação para canal oficial.',
      'Urgência, ameaça de bloqueio, link externo, pedido de sigilo e solicitação de código.',
      'Aviso público em site institucional e ausência de pedido de ação imediata.',
      'Notificação dentro de aplicativo oficial já instalado.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q027',
    moduleId: 'm1',
    difficulty: 'advanced',
    topic: 'reação-segura',
    question: 'Qual alternativa representa melhor uma reação segura diante de suspeita de golpe em andamento?',
    options: [
      'Agir rapidamente para cumprir as instruções antes do prazo informado.',
      'Interromper a interação, evitar novas ações, preservar elementos do contato e buscar confirmação em canal oficial independente.',
      'Negociar com o suposto atendente até obter mais detalhes.',
      'Apagar registros para evitar exposição de dados pessoais.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q028',
    moduleId: 'm1',
    difficulty: 'advanced',
    topic: 'governanca',
    question: 'Qual afirmação melhor representa a lógica de governança no enfrentamento a fraudes digitais?',
    options: [
      'A prevenção depende de ações isoladas e não coordenadas.',
      'A resposta efetiva exige integração entre prevenção, detecção, comunicação, capacitação, compartilhamento de informações e investigação quando cabível.',
      'A governança é desnecessária quando o usuário possui antivírus.',
      'Apenas a repressão posterior é relevante.',
    ],
    answer: 1,
  },
  {
    id: 'm1-q029',
    moduleId: 'm1',
    difficulty: 'advanced',
    topic: 'limites-prevencao',
    question: 'Por que o módulo afirma que prevenção não é culpabilização da vítima?',
    options: [
      'Porque a prevenção busca ampliar a capacidade de decisão segura e reduzir oportunidades para o criminoso, sem transferir ao cidadão a responsabilidade pelo crime.',
      'Porque vítimas nunca devem adotar medidas de segurança.',
      'Porque campanhas preventivas são juridicamente irrelevantes.',
      'Porque todos os golpes são inevitáveis.',
    ],
    answer: 0,
  },
  {
    id: 'm1-q030',
    moduleId: 'm1',
    difficulty: 'advanced',
    topic: 'síntese',
    question: 'Qual alternativa sintetiza melhor o aprendizado esperado ao final do Módulo 1?',
    options: [
      'O aluno deve memorizar nomes de instituições, sem relação com condutas práticas.',
      'O aluno deve compreender o ecossistema de segurança digital, reconhecer sinais iniciais de golpe e saber adotar uma primeira resposta segura.',
      'O aluno deve aprender a investigar tecnicamente autores de crimes digitais.',
      'O aluno deve substituir todos os canais oficiais por buscas em redes sociais.',
    ],
    answer: 1,
  },
]