export const checklistCategories = [
  'Golpes e fraudes digitais',
  'Transações e consumo seguro',
  'Dispositivos e redes',
  'Autenticação e contas',
  'Privacidade e proteção de dados',
  'Desinformação e conteúdo falso',
  'Resposta a incidentes e denúncia',
]

export const checklistModules = [
  'Módulo 1',
  'Módulo 2',
  'Módulo 3',
  'Módulo 4',
  'Módulo 5',
  'Módulo 6',
  'Transversal',
]

export const practicalChecklists = [
  {
    id: 'antes-de-clicar-link',
    title: 'Antes de clicar em um link',
    situation: 'Recebi um link por e-mail, SMS, WhatsApp, rede social ou QR Code.',
    category: 'Golpes e fraudes digitais',
    relatedModule: 'Módulo 5',
    description: 'Use este checklist para reduzir o risco de phishing, malware e páginas falsas.',
    items: [
      'Verifique se eu esperava receber essa mensagem.',
      'Observe se há urgência, ameaça, promoção exagerada ou pedido de sigilo.',
      'Confira o remetente e desconfie de erros, encurtadores ou endereços estranhos.',
      'Não informe senhas, códigos, tokens ou dados bancários após abrir o link.',
      'Prefira acessar o serviço digitando o endereço oficial no navegador.',
    ],
    finalGuidance: 'Na dúvida, não clique. Confirme por canal oficial independente.',
  },
  {
    id: 'antes-de-fazer-pix',
    title: 'Antes de fazer um Pix',
    situation: 'Vou realizar um pagamento ou transferência via Pix para pessoa ou empresa.',
    category: 'Transações e consumo seguro',
    relatedModule: 'Módulo 4',
    description: 'Evite golpes de engenharia social e transferências por engano.',
    items: [
      'Confirme a identidade do recebedor por outro meio (ligação ou pessoalmente).',
      'Confira o nome completo, CPF/CNPJ e banco do destino na tela de confirmação.',
      'Desconfie de pedidos urgentes de dinheiro vindo de conhecidos com número novo.',
      'Evite fazer Pix sob pressão emocional ou promessa de lucro imediato.',
      'Verifique se o QR Code ou chave Pix veio de um canal oficial.',
    ],
    finalGuidance: 'Pix é instantâneo e difícil de reverter. Confira tudo antes de confirmar.',
  },
  {
    id: 'ligacao-do-banco',
    title: 'Se recebi ligação do banco',
    situation: 'Alguém ligou dizendo ser do banco sobre uma suposta fraude ou transação suspeita.',
    category: 'Transações e consumo seguro',
    relatedModule: 'Módulo 4',
    description: 'Proteja-se contra o golpe da falsa central de atendimento.',
    items: [
      'Desligue imediatamente se pedirem senha, token ou transferência.',
      'Não instale aplicativos de "suporte" ou "segurança" pedidos por telefone.',
      'Desconfie se a pessoa disser que a ligação será "transferida para a polícia".',
      'Ligue para o seu banco usando o número que está no verso do seu cartão.',
      'Use um telefone diferente para ligar para o banco, se possível.',
    ],
    finalGuidance: 'Bancos nunca pedem senhas, tokens ou transferências por telefone.',
  },
  {
    id: 'celular-furtado',
    title: 'Se meu celular foi furtado',
    situation: 'Meu dispositivo móvel foi roubado, furtado ou perdido.',
    category: 'Dispositivos e redes',
    relatedModule: 'Módulo 6',
    description: 'Ações imediatas para proteger seus dados e contas bancárias.',
    items: [
      'Avise seus bancos para bloquear o acesso às contas e cartões.',
      'Acesse o portal Celular Seguro (Governo Federal) para bloqueio centralizado.',
      'Mude as senhas de e-mail, redes sociais e aplicativos de mensagens.',
      'Comunique a operadora para bloquear a linha (chip/IMEI).',
      'Registre um Boletim de Ocorrência (BO) na delegacia eletrônica.',
    ],
    finalGuidance: 'A agilidade no bloqueio das contas bancárias é a prioridade número um.',
  },
  {
    id: 'dados-vazaram',
    title: 'Se meus dados vazaram',
    situation: 'Recebi notícia ou alerta de que minhas informações pessoais foram expostas.',
    category: 'Privacidade e proteção de dados',
    relatedModule: 'Módulo 5',
    description: 'Como mitigar os danos após um vazamento de dados.',
    items: [
      'Troque imediatamente a senha da conta envolvida e de contas que usavam a mesma senha.',
      'Ative a verificação em duas etapas em todos os seus serviços importantes.',
      'Fique alerta a e-mails ou mensagens de phishing muito convincentes.',
      'Monitore seu extrato bancário e o Registrato do Banco Central.',
      'Se houver indício de fraude, registre um Boletim de Ocorrência.',
    ],
    finalGuidance: 'Dados vazados facilitam golpes de engenharia social. Redobre a atenção.',
  },
  {
    id: 'proteger-contas',
    title: 'Como proteger minhas contas',
    situation: 'Quero aumentar a segurança do meu e-mail, redes sociais e bancos.',
    category: 'Autenticação e contas',
    relatedModule: 'Módulo 2',
    description: 'Medidas preventivas fundamentais de higiene digital.',
    items: [
      'Use senhas fortes, longas e exclusivas para cada serviço.',
      'Ative a verificação em duas etapas (MFA) em todas as contas.',
      'Use aplicativos de autenticação em vez de SMS, quando disponível.',
      'Cadastre e mantenha atualizados seus meios de recuperação de conta.',
      'Revise periodicamente os dispositivos conectados nas configurações de segurança.',
    ],
    finalGuidance: 'A verificação em duas etapas é a proteção mais eficaz contra invasões.',
  },
  {
    id: 'compras-online',
    title: 'Como comprar online com segurança',
    situation: 'Estou pesquisando produtos ou prestes a fechar uma compra na internet.',
    category: 'Transações e consumo seguro',
    relatedModule: 'Módulo 4',
    description: 'Evite sites falsos e produtos que nunca serão entregues.',
    items: [
      'Verifique se o site é o oficial e se possui o cadeado de segurança (HTTPS).',
      'Pesquise a reputação da loja em sites como o Reclame Aqui.',
      'Desconfie de preços excessivamente abaixo da média do mercado.',
      'Use cartão virtual para compras online, se disponível no seu app bancário.',
      'Dê preferência a plataformas com sistemas de pagamento garantido e políticas claras de reembolso.',
    ],
    finalGuidance: 'Na dúvida sobre a loja, não informe os dados do seu cartão.',
  },
  {
    id: 'boatos-deepfakes',
    title: 'Como identificar boatos e deepfakes',
    situation: 'Recebi um vídeo ou mensagem alarmista com informações surpreendentes.',
    category: 'Desinformação e conteúdo falso',
    relatedModule: 'Módulo 1',
    description: 'Não se deixe enganar por conteúdos falsos ou manipulados por IA.',
    items: [
      'Verifique se a notícia foi publicada em portais de jornalismo confiáveis.',
      'Observe se o vídeo tem falhas na fala, movimentos estranhos ou baixa qualidade.',
      'Desconfie de pedidos de dinheiro feitos por "autoridades" em vídeos de redes sociais.',
      'Leia além do título e verifique a data de publicação da informação.',
      'Não compartilhe sem ter certeza da veracidade da informação.',
    ],
    finalGuidance: 'Conteúdos sensacionalistas e urgentes costumam ser iscas para desinformação.',
  },
  {
    id: 'evidencias-digitais',
    title: 'Como preservar evidências digitais',
    situation: 'Fui vítima de um crime ou golpe e preciso guardar evidências digitais.',
    category: 'Resposta a incidentes e denúncia',
    relatedModule: 'Módulo 6',
    description: 'Garanta que as evidências sejam preservadas adequadamente para uso oficial.',
    items: [
      'Tire prints (capturas de tela) de todas as conversas e perfis envolvidos.',
      'Não apague as mensagens ou o histórico de chamadas com o golpista.',
      'Guarde os comprovantes de Pix, transferências e boletos pagos.',
      'Salve o cabeçalho completo de e-mails suspeitos recebidos.',
      'Anote as URLs (endereços dos sites) e IDs das contas criminosas.',
    ],
    finalGuidance: 'Evidências digitais são voláteis. Guarde tudo imediatamente após o incidente.',
  },
  {
    id: 'apos-cair-em-golpe',
    title: 'Como agir após cair em um golpe',
    situation: 'Percebi que fui vítima de uma fraude financeira ou digital.',
    category: 'Resposta a incidentes e denúncia',
    relatedModule: 'Módulo 6',
    description: 'Ações imediatas para contenção de danos e denúncia.',
    items: [
      'Contate seu banco imediatamente para tentar bloquear o valor (Mecanismo Especial de Devolução).',
      'Registre um Boletim de Ocorrência (BO) detalhando o ocorrido e anexando as evidências salvas.',
      'Denuncie o perfil ou número golpista na plataforma onde ocorreu o contato.',
      'Comunique parentes e amigos caso o golpista esteja usando sua identidade.',
      'Procure orientação jurídica ou órgãos de defesa do consumidor, se necessário.',
    ],
    finalGuidance: 'Agir rápido ao acionar as instituições oficiais pelos canais de atendimento autorizados ajuda na contenção de danos e na proteção de terceiros.',
  },
]
