export const glossaryCategories = [
  'Golpes e fraudes digitais',
  'Autenticação e contas',
  'Privacidade e proteção de dados',
  'Dispositivos e redes',
  'Resposta a incidentes e denúncia',
  'Desinformação e conteúdo falso',
]

export const glossaryEntries = [
  {
    term: 'Phishing',
    category: 'Golpes e fraudes digitais',
    module: 'Módulo 5',
    definition: 'Tentativa de obter dados, senhas, códigos ou pagamentos por mensagens, e-mails, sites, ligações ou links falsos.',
    guidance: 'Não clique em links inesperados; acesse o serviço digitando o endereço oficial ou usando o aplicativo legítimo.',
    example: 'Um SMS dizendo que sua conta bancária foi bloqueada e pedindo para clicar em um link urgente.',
    priority: true,
  },
  {
    term: 'Engenharia social',
    category: 'Golpes e fraudes digitais',
    module: 'Módulo 1',
    definition: 'Uso de manipulação, pressão emocional ou falsa confiança para induzir a vítima a tomar uma decisão insegura.',
    guidance: 'Pause antes de agir e confirme a situação por outro canal quando houver pressão ou urgência.',
    example: 'Alguém ligando e fingindo ser do suporte técnico para pedir sua senha.',
    priority: true,
  },
  {
    term: 'Falsa central de atendimento',
    category: 'Golpes e fraudes digitais',
    module: 'Módulo 4',
    definition: 'Golpe em que o criminoso se passa por central de atendimento de banco ou empresa para pedir dados, códigos ou transferências.',
    guidance: 'Encerre o contato e procure a instituição por canal oficial independente. Bancos não pedem senhas ou transferências por telefone.',
    example: 'Receber ligação de um suposto funcionário do banco solicitando um Pix de teste para cancelar uma transação suspeita.',
    priority: true,
  },
  {
    term: 'Perfil falso',
    category: 'Golpes e fraudes digitais',
    module: 'Módulo 5',
    definition: 'Conta em rede social criada para se passar por outra pessoa ou empresa, geralmente para aplicar golpes em contatos próximos.',
    guidance: 'Se receber pedido de dinheiro de conhecido por número novo, ligue para a pessoa pelo número antigo para confirmar.',
    example: 'Um criminoso cria um perfil no WhatsApp usando a foto de um familiar e envia mensagens pedindo dinheiro emprestado.',
    priority: true,
  },
  {
    term: 'Link malicioso',
    category: 'Golpes e fraudes digitais',
    module: 'Módulo 5',
    definition: 'Endereço eletrônico que, ao ser clicado, direciona para sites falsos ou inicia o download de vírus.',
    guidance: 'Passe o mouse (ou pressione longamente) sobre o link para ver o endereço real antes de clicar.',
    example: 'Receber um link encurtado via e-mail que promete um cupom de desconto, mas redireciona para um site de coleta de dados bancários.',
    priority: true,
  },
  {
    term: 'QR Code falso',
    category: 'Golpes e fraudes digitais',
    module: 'Módulo 4',
    definition: 'Código visual adulterado que direciona o pagamento ou o acesso para criminosos em vez do destino legítimo.',
    guidance: 'Antes de confirmar o pagamento via QR Code, confira o nome do recebedor na tela do seu aplicativo.',
    example: 'Um cartaz de cobrança de estacionamento com um QR Code colado por cima do original, direcionando a transferência para a conta do golpista.',
    priority: true,
  },
  {
    term: 'Malware',
    category: 'Golpes e fraudes digitais',
    module: 'Módulo 5',
    definition: 'Programa ou arquivo malicioso criado para comprometer dispositivos, capturar informações ou espionar atividades.',
    guidance: 'Instale aplicativos apenas por lojas oficiais e mantenha o sistema atualizado.',
    example: 'Baixar um arquivo que promete liberar gratuitamente um jogo pago, mas que secretamente instala um programa espião no celular.',
    priority: true,
  },
  {
    term: 'Ransomware',
    category: 'Golpes e fraudes digitais',
    module: 'Módulo 5',
    definition: 'Tipo de malware que bloqueia arquivos do usuário e exige pagamento (resgate) para liberá-los.',
    guidance: 'A melhor defesa é ter backups (cópias de segurança) atualizados e fora do dispositivo principal.',
    example: 'Um vírus recebido por e-mail que criptografa todas as fotos e documentos da vítima, exibindo uma cobrança em dinheiro para resgatar os arquivos.',
    priority: true,
  },
  {
    term: 'Golpe do falso prêmio',
    category: 'Golpes e fraudes digitais',
    module: 'Módulo 5',
    definition: 'Mensagem informando que você ganhou um sorteio ou brinde, condicionada ao pagamento de uma "taxa de envio" ou fornecimento de dados.',
    guidance: 'Se você não participou de um sorteio, não há prêmio a receber. Nunca pague para receber um prêmio.',
  },
  {
    term: 'Falsa venda / Marketplace',
    category: 'Golpes e fraudes digitais',
    module: 'Módulo 4',
    definition: 'Anúncios de produtos com preços muito abaixo do mercado em plataformas de venda direta, onde o vendedor desaparece após o pagamento.',
    guidance: 'Dê preferência a pagamentos dentro da plataforma e evite transferências diretas antes de ver o produto.',
  },
  {
    term: 'Autenticação forte',
    category: 'Autenticação e contas',
    module: 'Módulo 2',
    definition: 'Uso de múltiplos fatores para confirmar a identidade, tornando o acesso muito mais seguro do que apenas com senha.',
    guidance: 'Sempre que possível, use biometria ou chaves físicas como fator de autenticação.',
  },
  {
    term: 'Verificação em duas etapas',
    category: 'Autenticação e contas',
    module: 'Módulo 2',
    definition: 'Camada adicional de proteção que exige uma segunda confirmação (código, aplicativo ou biometria) além da senha.',
    guidance: 'Ative em todas as contas importantes, especialmente e-mail, redes sociais e aplicativos de mensagens.',
    example: 'Configurar seu aplicativo de mensagens para exigir um código numérico temporário (PIN) enviado por SMS ou gerado no celular ao fazer login.',
    priority: true,
  },
  {
    term: 'Senha forte',
    category: 'Autenticação e contas',
    module: 'Módulo 2',
    definition: 'Sequência longa e complexa, que mistura letras, números e símbolos, sendo difícil de ser adivinhada por humanos ou máquinas.',
    guidance: 'Não reutilize a mesma senha em sites diferentes. Se uma vazar, as outras estarão seguras.',
    example: 'Usar uma frase secreta longa e personalizada como "BoloDeCenoura#Seguro2026!" em vez de datas de aniversário simples.',
    priority: true,
  },
  {
    term: 'Gerenciador de senhas',
    category: 'Autenticação e contas',
    module: 'Módulo 2',
    definition: 'Aplicativo que armazena todas as suas senhas de forma segura, permitindo usar senhas complexas e únicas para cada site.',
    guidance: 'Com um gerenciador, você só precisa decorar uma única "senha mestra" muito forte.',
  },
  {
    term: 'Canal oficial',
    category: 'Autenticação e contas',
    module: 'Módulo 1',
    definition: 'Meio de comunicação legítimo da empresa (site oficial, app da loja, telefone oficial) para realizar operações seguras.',
    guidance: 'Sempre procure o canal oficial por conta própria em vez de usar links enviados por terceiros.',
  },
  {
    term: 'Privacidade',
    category: 'Privacidade e proteção de dados',
    module: 'Módulo 2',
    definition: 'Direito de controlar como suas informações pessoais são coletadas, usadas e compartilhadas por empresas e pessoas.',
    guidance: 'Leia as permissões que os aplicativos pedem e negue o acesso a dados que não são necessários para a função do app.',
  },
  {
    term: 'Cookies',
    category: 'Privacidade e proteção de dados',
    module: 'Módulo 2',
    definition: 'Arquivos salvos pelo navegador que lembram suas preferências e atividades em sites, mas que também podem ser usados para rastreamento.',
    guidance: 'Limpe periodicamente os cookies do seu navegador e recuse cookies de rastreamento não essenciais.',
  },
  {
    term: 'Vazamento de dados',
    category: 'Privacidade e proteção de dados',
    module: 'Módulo 5',
    definition: 'Incidente onde informações confidenciais são acessadas ou expostas indevidamente para pessoas não autorizadas.',
    guidance: 'Se seus dados vazarem, troque as senhas envolvidas e fique alerta a tentativas de Phishing direcionadas.',
    example: 'Uma invasão ao sistema de uma loja virtual que expõe CPFs, e-mails e telefones de clientes em fóruns públicos na internet.',
    priority: true,
  },
  {
    term: 'Backup',
    category: 'Dispositivos e redes',
    module: 'Módulo 2',
    definition: 'Cópia de segurança de arquivos importantes guardada em local diferente do original (nuvem ou HD externo).',
    guidance: 'Mantenha o backup automático ativado no celular para fotos e contatos.',
  },
  {
    term: 'Antivírus',
    category: 'Dispositivos e redes',
    module: 'Módulo 3',
    definition: 'Software que detecta, previne e remove programas maliciosos (vírus) do seu computador ou celular.',
    guidance: 'Não basta ter o antivírus instalado; ele precisa estar sempre atualizado para reconhecer novas ameaças.',
  },
  {
    term: 'Firewall',
    category: 'Dispositivos e redes',
    module: 'Módulo 3',
    definition: 'Barreira de segurança que monitora o tráfego de rede e bloqueia conexões suspeitas que tentam entrar ou sair do dispositivo.',
    guidance: 'Mantenha o firewall do sistema operacional sempre ativado.',
  },
  {
    term: 'Rede Wi-Fi',
    category: 'Dispositivos e redes',
    module: 'Módulo 3',
    definition: 'Tecnologia de conexão sem fio. Redes públicas (shoppings, aeroportos) são menos seguras que redes domésticas protegidas.',
    guidance: 'Evite acessar contas bancárias ou fazer compras usando redes Wi-Fi públicas e abertas.',
    example: 'Conectar-se à rede sem fio gratuita de uma cafeteria pública para realizar compras online com cartão de crédito.',
    priority: true,
  },
  {
    term: 'Roteador',
    category: 'Dispositivos e redes',
    module: 'Módulo 3',
    definition: 'Aparelho que distribui a internet na sua casa. Se estiver mal configurado, pode ser uma porta de entrada para invasores.',
    guidance: 'Troque a senha de administração que vem de fábrica no seu roteador.',
  },
  {
    term: 'Preservação de evidências',
    category: 'Resposta a incidentes e denúncia',
    module: 'Módulo 6',
    definition: 'Ato de salvar e guardar registros de um incidente digital (como prints, e-mails, comprovantes e extratos) sem alterá-los, para apresentação às instituições competentes.',
    guidance: 'Não apague as conversas com perfis suspeitos antes de salvar todas as telas e informações importantes.',
    example: 'Tirar prints completos de conversas com golpistas contendo número de telefone, foto do perfil, chaves Pix e e-mails recebidos.',
    priority: true,
  },
  {
    term: 'Denúncia',
    category: 'Resposta a incidentes e denúncia',
    module: 'Módulo 6',
    definition: 'Informar formalmente um crime ou fraude às autoridades (Boletim de Ocorrência) ou às plataformas envolvidas.',
    guidance: 'Denuncie perfis golpistas nas próprias redes sociais para que a conta seja suspensa.',
    example: 'Registrar um Boletim de Ocorrência online na delegacia eletrônica após constatar que foi vítima de golpe financeiro na internet.',
    priority: true,
  },
  {
    term: 'Boato / Fake News',
    category: 'Desinformação e conteúdo falso',
    module: 'Módulo 1',
    definition: 'Informação falsa ou distorcida espalhada como se fosse verdade, geralmente para causar pânico ou influenciar opiniões.',
    guidance: 'Sempre cheque a informação em sites confiáveis antes de compartilhar mensagens alarmistas.',
  },
  {
    term: 'Deepfake',
    category: 'Desinformação e conteúdo falso',
    module: 'Módulo 5',
    definition: 'Vídeo ou áudio criado com inteligência artificial para imitar a voz e o rosto de uma pessoa real dizendo coisas que ela nunca disse.',
    guidance: 'Desconfie de vídeos de autoridades ou famosos pedindo transferências ou promovendo investimentos "milagrosos".',
    example: 'Um vídeo circulando nas redes sociais onde o rosto de uma celebridade é simulado por inteligência artificial para promover um produto fraudulento.',
    priority: true,
  },
]
