export const libraryDocuments = [
  {
    title: 'Fascículo Proteção de Dados',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Privacidade e proteção de dados',
    type: 'Fascículo',
    relatedModule: 'Módulo 2',
    description: 'Material educativo com orientações para reduzir exposição de dados, proteger contas e agir preventivamente.',
    url: 'https://cartilha.cert.br/fasciculos/protecao-de-dados/fasciculo-protecao-de-dados.pdf',
  },
  {
    title: 'Fascículo Privacidade',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Privacidade e proteção de dados',
    type: 'Fascículo',
    relatedModule: 'Módulo 2',
    description: 'Cuidados com a privacidade e a exposição de informações no ambiente digital.',
    url: 'https://cartilha.cert.br/fasciculos/privacidade/fasciculo-privacidade.pdf',
  },
  {
    title: 'Fascículo Autenticação',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Privacidade e proteção de dados',
    type: 'Fascículo',
    relatedModule: 'Módulo 2',
    description: 'Orientações sobre senhas, verificação em duas etapas e proteção de acesso.',
    url: 'https://cartilha.cert.br/fasciculos/autenticacao/fasciculo-autenticacao.pdf',
  },
  {
    title: 'Fascículo Backup',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Dispositivos e redes',
    type: 'Fascículo',
    relatedModule: 'Módulo 2',
    description: 'Importância e métodos para realizar cópias de segurança de arquivos importantes.',
    url: 'https://cartilha.cert.br/fasciculos/backup/fasciculo-backup.pdf',
  },
  {
    title: 'Fascículo Computadores',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Dispositivos e redes',
    type: 'Fascículo',
    relatedModule: 'Módulo 3',
    description: 'Dicas de segurança para uso e configuração de computadores pessoais.',
    url: 'https://cartilha.cert.br/fasciculos/computadores/fasciculo-computadores.pdf',
  },
  {
    title: 'Fascículo Celulares e Tablets',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Dispositivos e redes',
    type: 'Fascículo',
    relatedModule: 'Módulo 3',
    description: 'Cuidados essenciais para a proteção de dispositivos móveis.',
    url: 'https://cartilha.cert.br/fasciculos/celulares-e-tablets/fasciculo-celulares-e-tablets.pdf',
  },
  {
    title: 'Fascículo Furto de Celular',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Resposta a incidentes e denúncia',
    type: 'Fascículo',
    relatedModule: 'Módulos 3 e 6',
    description: 'Medidas preventivas e ações imediatas após o furto ou perda do celular.',
    url: 'https://cartilha.cert.br/fasciculos/furto-de-celular/fasciculo-furto-de-celular.pdf',
  },
  {
    title: 'Fascículo Redes',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Dispositivos e redes',
    type: 'Fascículo',
    relatedModule: 'Módulo 3',
    description: 'Cuidados com redes Wi-Fi, roteadores e conexões domésticas e públicas.',
    url: 'https://cartilha.cert.br/fasciculos/redes/fasciculo-redes.pdf',
  },
  {
    title: 'Fascículo Redes Sociais',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Privacidade e proteção de dados',
    type: 'Fascículo',
    relatedModule: 'Módulo 5',
    description: 'Uso seguro de redes sociais, proteção de perfil e privacidade de publicações.',
    url: 'https://cartilha.cert.br/fasciculos/redes-sociais/fasciculo-redes-sociais.pdf',
  },
  {
    title: 'Fascículo Códigos Maliciosos',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Golpes e fraudes digitais',
    type: 'Fascículo',
    relatedModule: 'Módulos 3 e 5',
    description: 'Entenda o que são vírus, cavalos de troia e outros programas maliciosos.',
    url: 'https://cartilha.cert.br/fasciculos/codigos-maliciosos/fasciculo-codigos-maliciosos.pdf',
  },
  {
    title: 'Fascículo Banco via Internet',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Transações e consumo seguro',
    type: 'Fascículo',
    relatedModule: 'Módulo 4',
    description: 'Dicas para realizar transações bancárias online com segurança.',
    url: 'https://cartilha.cert.br/fasciculos/banco-via-internet/fasciculo-banco-via-internet.pdf',
  },
  {
    title: 'Fascículo Comércio via Internet',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Transações e consumo seguro',
    type: 'Fascículo',
    relatedModule: 'Módulo 4',
    description: 'Orientações para compras online e proteção do consumidor digital.',
    url: 'https://cartilha.cert.br/fasciculos/comercio-via-internet/fasciculo-comercio-via-internet.pdf',
  },
  {
    title: 'Fascículo Boatos',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Desinformação e conteúdo falso',
    type: 'Fascículo',
    relatedModule: 'Módulo 5',
    description: 'Como identificar notícias falsas e evitar a propagação de boatos.',
    url: 'https://cartilha.cert.br/fasciculos/boatos/fasciculo-boatos.pdf',
  },
  {
    title: 'Fascículo Vazamento de Dados',
    source: 'CERT.br / NIC.br / CGI.br',
    category: 'Privacidade e proteção de dados',
    type: 'Fascículo',
    relatedModule: 'Módulos 5 e 6',
    description: 'O que fazer quando suas informações pessoais são expostas indevidamente.',
    url: 'https://cartilha.cert.br/fasciculos/vazamento-de-dados/fasciculo-vazamento-de-dados.pdf',
  },
  {
    title: 'Glossário de Tipologias de Fraudes e Golpes Digitais',
    source: 'Aliança Nacional de Combate a Fraudes Bancárias Digitais',
    category: 'Golpes e fraudes digitais',
    type: 'Glossário',
    relatedModule: 'Módulo 5',
    description: 'Definições oficiais sobre as principais modalidades de fraudes e golpes bancários.',
    url: 'https://portal.febraban.org.br/pagina/3411/1136/pt-br/alianca-nacional',
  },
  {
    title: 'Plano de Ação Conjunta — Aliança Nacional',
    source: 'MJSP / FEBRABAN',
    category: 'Resposta a incidentes e denúncia',
    type: 'Documento oficial',
    relatedModule: 'Módulo 1',
    description: 'Documento detalhando a estratégia nacional para enfrentamento de fraudes digitais.',
    url: 'https://www.gov.br/mj/pt-br/assuntos/alianca-nacional-de-combate-a-fraudes-bancarias-digitais',
  },
  {
    title: 'Campanha #DigaNãoAosGolpes',
    source: 'FEBRABAN',
    category: 'Campanhas educativas',
    type: 'Portal de campanha',
    relatedModule: 'Módulos 4 e 6',
    description: 'Materiais e vídeos educativos da campanha nacional de prevenção a fraudes.',
    url: 'https://antifraude.febraban.org.br/',
  },
  {
    title: 'Campanha Think Twice',
    source: 'INTERPOL',
    category: 'Campanhas educativas',
    type: 'Campanha internacional',
    relatedModule: 'Módulo 5',
    description: 'Orientações globais sobre como identificar tentativas de fraude e golpes online.',
    url: 'https://www.interpol.int/en/Crimes/Cybercrime/Cyber-safety-campaigns',
  },
  {
    title: 'Combate a Crimes Cibernéticos — Polícia Federal',
    source: 'Polícia Federal',
    category: 'Resposta a incidentes e denúncia',
    type: 'Portal institucional',
    relatedModule: 'Módulo 6',
    description: 'Orientações e notícias sobre a atuação da PF no combate ao crime digital.',
    url: 'https://www.gov.br/pf/pt-br/assuntos/combate-a-crimes-ciberneticos',
  },
  {
    title: 'Comunica PF — Registro de Ocorrência',
    source: 'Polícia Federal',
    category: 'Resposta a incidentes e denúncia',
    type: 'Canal oficial',
    relatedModule: 'Módulo 6',
    description: 'Plataforma oficial para comunicação de crimes e indícios à Polícia Federal.',
    url: 'https://www.gov.br/pf/pt-br/canais_atendimento/comunicacao-de-crimes',
  },
  {
    title: 'Guia: Sofri um golpe, e agora?',
    source: 'MJSP',
    category: 'Resposta a incidentes e denúncia',
    type: 'Guia prático',
    relatedModule: 'Módulo 6',
    description: 'Passo a passo oficial para quem foi vítima de golpe digital.',
    url: 'https://www.gov.br/mj/pt-br/acesso-a-informacao/acoes-e-programas/sofri-um-golpe-e-agora',
  },
]

export const libraryCategories = [
  'Golpes e fraudes digitais',
  'Dispositivos e redes',
  'Privacidade e proteção de dados',
  'Transações e consumo seguro',
  'Desinformação e conteúdo falso',
  'Resposta a incidentes e denúncia',
  'Campanhas educativas',
]

export const librarySources = [...new Set(libraryDocuments.map((item) => item.source))].sort()
export const libraryTypes = [...new Set(libraryDocuments.map((item) => item.type))].sort()
