export const libraryDocuments = [
  {
    title: 'Polícia Federal — Combate a Crimes Cibernéticos',
    description: 'Página institucional com orientações e informações públicas da Polícia Federal sobre crimes cibernéticos.',
    source: 'Polícia Federal',
    type: 'Portal institucional',
    theme: 'Denúncia e investigação',
    module: 'Módulos 1 e 6',
    relatedModule: 'Módulos 1 e 6',
    url: 'https://www.gov.br/pf/pt-br/assuntos/combate-a-crimes-ciberneticos',
  },
  {
    title: 'Polícia Federal — Comunica PF',
    description: 'Canal oficial para comunicação de crimes à Polícia Federal, incluindo situações com elementos digitais.',
    source: 'Polícia Federal',
    type: 'Canal oficial',
    theme: 'Comunicação de crimes',
    module: 'Módulos 1 e 6',
    relatedModule: 'Módulos 1 e 6',
    url: 'https://www.gov.br/pf/pt-br/canais_atendimento/comunicacao-de-crimes',
  },
  {
    title: 'MJSP — Portal oficial',
    description: 'Portal público do Ministério da Justiça e Segurança Pública para consulta institucional e serviços relacionados.',
    source: 'MJSP',
    type: 'Portal institucional',
    theme: 'Cidadania e segurança pública',
    module: 'Transversal',
    relatedModule: 'Transversal',
    url: 'https://www.gov.br/mj/pt-br',
  },
  {
    title: 'MJSP — Aliança Nacional de Combate a Fraudes Bancárias Digitais',
    description: 'Página pública sobre a articulação nacional voltada ao enfrentamento de fraudes bancárias digitais.',
    source: 'MJSP',
    type: 'Programa público',
    theme: 'Fraudes bancárias digitais',
    module: 'Módulo 1',
    relatedModule: 'Módulo 1',
    url: 'https://www.gov.br/mj/pt-br/assuntos/alianca-nacional-de-combate-a-fraudes-bancarias-digitais',
  },
  {
    title: 'MJSP — Sofri um golpe, e agora?',
    description: 'Orientação oficial para primeiros passos após golpe, com foco em contenção, registro e comunicação adequada.',
    source: 'MJSP',
    type: 'Orientação pública',
    theme: 'Resposta a golpes',
    module: 'Módulos 4 e 6',
    relatedModule: 'Módulos 4 e 6',
    url: 'https://www.gov.br/mj/pt-br/acesso-a-informacao/acoes-e-programas/sofri-um-golpe-e-agora',
  },
  {
    title: 'FEBRABAN — Portal oficial',
    description: 'Portal institucional da Federação Brasileira de Bancos, com informações públicas do setor bancário.',
    source: 'FEBRABAN',
    type: 'Portal institucional',
    theme: 'Sistema financeiro',
    module: 'Transversal',
    relatedModule: 'Transversal',
    url: 'https://portal.febraban.org.br/',
  },
  {
    title: 'FEBRABAN — Aliança de Combate a Fraudes Digitais Bancárias',
    description: 'Página pública da iniciativa de combate a fraudes digitais bancárias vinculada à agenda da FEBRABAN.',
    source: 'FEBRABAN',
    type: 'Programa público',
    theme: 'Fraudes bancárias digitais',
    module: 'Módulo 1',
    relatedModule: 'Módulo 1',
    url: 'https://portal.febraban.org.br/pagina/3411/1136/pt-br/alianca-nacional',
  },
  {
    title: 'FEBRABAN — Campanha #DigaNãoAosGolpes',
    description: 'Campanha pública de prevenção a golpes e fraudes bancárias digitais.',
    source: 'FEBRABAN',
    type: 'Campanha pública',
    theme: 'Prevenção a golpes',
    module: 'Módulos 4 e 6',
    relatedModule: 'Módulos 4 e 6',
    url: 'https://portal.febraban.org.br/AntiFraude/',
  },
  {
    title: 'CERT.br — Fascículos da Cartilha de Segurança para Internet',
    description: 'Coleção pública de fascículos da Cartilha de Segurança para Internet do CERT.br.',
    source: 'CERT.br',
    type: 'Coleção',
    theme: 'Segurança digital',
    module: 'Módulo 1',
    relatedModule: 'Módulo 1',
    url: 'https://cartilha.cert.br/fasciculos/',
  },
  {
    title: 'CERT.br — Fascículo Autenticação',
    description: 'Material público sobre autenticação, senhas e mecanismos de proteção de contas.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Autenticação',
    module: 'Módulo 2',
    relatedModule: 'Módulo 2',
    url: 'https://cartilha.cert.br/fasciculos/autenticacao/fasciculo-autenticacao.pdf',
  },
  {
    title: 'CERT.br — Fascículo Backup',
    description: 'Material público sobre cópias de segurança e recuperação de dados.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Backup',
    module: 'Módulo 2',
    relatedModule: 'Módulo 2',
    url: 'https://cartilha.cert.br/fasciculos/backup/fasciculo-backup.pdf',
  },
  {
    title: 'CERT.br — Fascículo Privacidade',
    description: 'Material público sobre privacidade, exposição de dados e cuidados no ambiente digital.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Privacidade',
    module: 'Módulo 2',
    relatedModule: 'Módulo 2',
    url: 'https://cartilha.cert.br/fasciculos/privacidade/fasciculo-privacidade.pdf',
  },
  {
    title: 'CERT.br — Fascículo Proteção de Dados',
    description: 'Material público sobre proteção de dados pessoais e redução de exposição indevida.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Proteção de dados',
    module: 'Módulo 2',
    relatedModule: 'Módulo 2',
    url: 'https://cartilha.cert.br/fasciculos/protecao-de-dados/fasciculo-protecao-de-dados.pdf',
  },
  {
    title: 'CERT.br — Fascículo Vazamento de Dados',
    description: 'Material público sobre vazamento de dados, riscos associados e medidas de resposta.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Vazamento de dados',
    module: 'Módulos 2, 5 e 6',
    relatedModule: 'Módulos 2, 5 e 6',
    url: 'https://cartilha.cert.br/fasciculos/vazamento-de-dados/fasciculo-vazamento-de-dados.pdf',
  },
  {
    title: 'CERT.br — Fascículo Celulares e Tablets',
    description: 'Material público sobre cuidados de segurança em dispositivos móveis.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Dispositivos móveis',
    module: 'Módulo 3',
    relatedModule: 'Módulo 3',
    url: 'https://cartilha.cert.br/fasciculos/celulares-e-tablets/fasciculo-celulares-e-tablets.pdf',
  },
  {
    title: 'CERT.br — Fascículo Computadores',
    description: 'Material público sobre proteção e uso seguro de computadores pessoais.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Dispositivos',
    module: 'Módulo 3',
    relatedModule: 'Módulo 3',
    url: 'https://cartilha.cert.br/fasciculos/computadores/fasciculo-computadores.pdf',
  },
  {
    title: 'CERT.br — Fascículo Redes',
    description: 'Material público sobre cuidados com redes, conexões e acesso seguro.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Redes',
    module: 'Módulo 3',
    relatedModule: 'Módulo 3',
    url: 'https://cartilha.cert.br/fasciculos/redes/fasciculo-redes.pdf',
  },
  {
    title: 'CERT.br — Fascículo Trabalho Remoto',
    description: 'Material público sobre práticas seguras em trabalho remoto e acesso a recursos digitais.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Trabalho remoto',
    module: 'Módulo 3',
    relatedModule: 'Módulo 3',
    url: 'https://cartilha.cert.br/fasciculos/trabalho-remoto/fasciculo-trabalho-remoto.pdf',
  },
  {
    title: 'CERT.br — Fascículo Códigos Maliciosos',
    description: 'Material público sobre malware, formas de infecção e medidas preventivas.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Malware',
    module: 'Módulos 3 e 5',
    relatedModule: 'Módulos 3 e 5',
    url: 'https://cartilha.cert.br/fasciculos/codigos-maliciosos/fasciculo-codigos-maliciosos.pdf',
  },
  {
    title: 'CERT.br — Fascículo Furto de Celular',
    description: 'Material público sobre prevenção, contenção de danos e providências após furto de celular.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Dispositivos móveis',
    module: 'Módulos 3 e 6',
    relatedModule: 'Módulos 3 e 6',
    url: 'https://cartilha.cert.br/fasciculos/furto-de-celular/fasciculo-furto-de-celular.pdf',
  },
  {
    title: 'CERT.br — Fascículo Banco via Internet',
    description: 'Material público sobre cuidados ao usar serviços bancários pela internet.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Banco digital',
    module: 'Módulo 4',
    relatedModule: 'Módulo 4',
    url: 'https://cartilha.cert.br/fasciculos/banco-via-internet/fasciculo-banco-via-internet.pdf',
  },
  {
    title: 'CERT.br — Fascículo Comércio via Internet',
    description: 'Material público sobre compras online, consumo digital e cuidados em transações.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Comércio eletrônico',
    module: 'Módulo 4',
    relatedModule: 'Módulo 4',
    url: 'https://cartilha.cert.br/fasciculos/comercio-via-internet/fasciculo-comercio-via-internet.pdf',
  },
  {
    title: 'CERT.br — Fascículo Golpes: Evite Fraudes',
    description: 'Material público com orientações para reconhecer e evitar fraudes digitais.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Prevenção a golpes',
    module: 'Módulos 4 e 5',
    relatedModule: 'Módulos 4 e 5',
    url: 'https://cartilha.cert.br/fasciculos/golpes-evite-fraudes/fasciculo-golpes-evite-fraudes.pdf',
  },
  {
    title: 'CERT.br — Fascículo Golpes: Não se Deixe Enganar',
    description: 'Material público sobre tipos de golpes, sinais de alerta e atitudes preventivas.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Catálogo de golpes',
    module: 'Módulo 5',
    relatedModule: 'Módulo 5',
    url: 'https://cartilha.cert.br/fasciculos/golpes/fasciculo-golpes.pdf',
  },
  {
    title: 'CERT.br — Fascículo Boatos',
    description: 'Material público sobre boatos, desinformação e cuidados antes de compartilhar conteúdo.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Desinformação',
    module: 'Módulo 5',
    relatedModule: 'Módulo 5',
    url: 'https://cartilha.cert.br/fasciculos/boatos/fasciculo-boatos.pdf',
  },
  {
    title: 'CERT.br — Fascículo Redes Sociais',
    description: 'Material público sobre segurança, privacidade e exposição em redes sociais.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Redes sociais',
    module: 'Módulo 5',
    relatedModule: 'Módulo 5',
    url: 'https://cartilha.cert.br/fasciculos/redes-sociais/fasciculo-redes-sociais.pdf',
  },
  {
    title: 'CERT.br — Fascículo Golpes: Caiu? Veja o que Fazer',
    description: 'Material público sobre providências após cair em golpe, contenção de danos e próximos passos.',
    source: 'CERT.br',
    type: 'PDF',
    theme: 'Resposta a golpes',
    module: 'Módulo 6',
    relatedModule: 'Módulo 6',
    url: 'https://cartilha.cert.br/fasciculos/golpes-o-que-fazer/fasciculo-golpes-o-que-fazer.pdf',
  },
]

export const librarySources = [...new Set(libraryDocuments.map((item) => item.source))]
export const libraryThemes = [...new Set(libraryDocuments.map((item) => item.theme))]
export const libraryTypes = [...new Set(libraryDocuments.map((item) => item.type))]
