export const videoThemes = [
  'Golpes e fraudes digitais',
  'Transações e consumo seguro',
  'Privacidade e proteção de dados',
  'Dispositivos e redes',
  'Desinformação e conteúdo falso',
  'Resposta a incidentes e denúncia',
  'Campanhas educativas',
]

export const videoSources = [
  'MJSP',
  'Polícia Federal',
  'FEBRABAN',
  'Banco Central',
  'CERT.br',
  'NIC.br',
  'INTERPOL',
  'CGI.br',
]

export const videoModules = [
  'Módulo 1',
  'Módulo 2',
  'Módulo 3',
  'Módulo 4',
  'Módulo 5',
  'Módulo 6',
  'Transversal',
]

export const educationalVideos = [
  {
    title: 'Campanha #DigaNãoAosGolpes',
    source: 'FEBRABAN',
    theme: 'Campanhas educativas',
    type: 'Vídeo educativo',
    relatedModule: 'Módulo 4',
    modules: ['Módulo 4'],
    tags: ['fraudes', 'segurança bancária', 'cartão de crédito', 'prevenção'],
    duration: '01:00',
    description: 'Vídeo da campanha nacional de prevenção a fraudes e golpes bancários.',
    status: 'Disponível',
    url: 'https://antifraude.febraban.org.br/',
  },
  {
    title: 'Think Twice - INTERPOL',
    source: 'INTERPOL',
    theme: 'Golpes e fraudes digitais',
    type: 'Campanha internacional',
    relatedModule: 'Módulo 5',
    modules: ['Módulo 5'],
    tags: ['phishing', 'romance scams', 'ransomware', 'malware', 'ia generativa'],
    duration: '00:45',
    description: 'Campanha global da INTERPOL sobre como identificar tentativas de fraude online.',
    status: 'Disponível',
    url: 'https://www.interpol.int/en/Crimes/Cybercrime/Cyber-safety-campaigns',
  },
  {
    title: 'Furto de Celular: O que fazer?',
    source: 'MJSP',
    theme: 'Resposta a incidentes e denúncia',
    type: 'Guia em vídeo',
    relatedModule: 'Módulo 6',
    modules: ['Módulo 6'],
    tags: ['furto', 'roubo', 'celular seguro', 'bloqueio', 'dispositivo'],
    duration: '02:30',
    description: 'Orientações oficiais do Ministério da Justiça sobre procedimentos após furto de dispositivo.',
    status: 'Disponível',
    url: 'https://www.gov.br/mj/pt-br/assuntos/celular-seguro',
  },
  {
    title: 'Entendendo o Phishing',
    source: 'CERT.br',
    theme: 'Golpes e fraudes digitais',
    type: 'Vídeo educativo',
    relatedModule: 'Módulo 5',
    modules: ['Módulo 5'],
    tags: ['phishing', 'links suspeitos', 'e-mail', 'engenharia social'],
    duration: '03:15',
    description: 'Explicação detalhada sobre como funcionam os ataques de phishing e como se proteger.',
    status: 'Disponível',
    url: 'https://cartilha.cert.br/videos/',
  },
  {
    title: 'Segurança Bancária Digital',
    source: 'Banco Central',
    theme: 'Transações e consumo seguro',
    type: 'Vídeo institucional',
    relatedModule: 'Módulo 4',
    modules: ['Módulo 4'],
    tags: ['banco', 'internet banking', 'pix', 'transações'],
    duration: '02:00',
    description: 'Orientações do Banco Central sobre o uso seguro de canais digitais e PIX.',
    status: 'Disponível',
    url: 'https://www.bcb.gov.br/cidadaniafinanceira/segurancadigital',
  },
  {
    title: 'Engenharia Social: O Fator Humano',
    source: 'Polícia Federal',
    theme: 'Golpes e fraudes digitais',
    type: 'Vídeo educativo',
    relatedModule: 'Módulo 1',
    modules: ['Módulo 1'],
    tags: ['engenharia social', 'persuasão', 'fator humano', 'golpes'],
    duration: '04:00',
    description: 'Como criminosos utilizam a persuasão para obter dados sensíveis.',
    status: 'Em preparação',
    url: '',
  },
  {
    title: 'Privacidade e Dados Pessoais',
    source: 'NIC.br',
    theme: 'Privacidade e proteção de dados',
    type: 'Vídeo educativo',
    relatedModule: 'Módulo 2',
    modules: ['Módulo 2'],
    tags: ['privacidade', 'lgpd', 'dados pessoais'],
    duration: '05:30',
    description: 'A importância da LGPD e do controle sobre seus dados pessoais na rede.',
    status: 'Disponível',
    url: 'https://nic.br/videos/',
  },
  {
    title: 'Combate à Desinformação',
    source: 'CGI.br',
    theme: 'Desinformação e conteúdo falso',
    type: 'Campanha educativa',
    relatedModule: 'Módulo 1',
    modules: ['Módulo 1'],
    tags: ['desinformação', 'boatos', 'fake news'],
    duration: '03:00',
    description: 'Como identificar boatos e notícias falsas no ambiente digital.',
    status: 'Disponível',
    url: 'https://cgi.br/videos/',
  },
  {
    title: 'Segurança de Dispositivos Móveis',
    source: 'CERT.br',
    theme: 'Dispositivos e redes',
    type: 'Vídeo educativo',
    relatedModule: 'Módulo 3',
    modules: ['Módulo 3'],
    tags: ['celular', 'tablet', 'smartphone', 'mobile', 'segurança'],
    duration: '03:45',
    description: 'Configurações essenciais para manter seu smartphone seguro contra invasões.',
    status: 'Disponível',
    url: 'https://cartilha.cert.br/videos/',
  },
  {
    title: 'Resposta a Incidentes Digitais',
    source: 'Polícia Federal',
    theme: 'Resposta a incidentes e denúncia',
    type: 'Vídeo institucional',
    relatedModule: 'Módulo 6',
    modules: ['Módulo 6'],
    tags: ['resposta a incidentes', 'denúncia', 'preservação de provas', 'boletim de ocorrência'],
    duration: '02:15',
    description: 'Como denunciar crimes cibernéticos e preservar evidências digitais.',
    status: 'Em preparação',
    url: '',
  },
]
